# Introduction to Numpy

Python lists:

* are very flexible
* don't require uniform numerical types
* are very easy to modify (inserting or appending objects).

However, flexibility often comes at the cost of performance, and lists are not the ideal object for numerical calculations.

This is where **Numpy** comes in. Numpy is a Python module that defines a powerful n-dimensional array object that uses C and Fortran code behind the scenes to provide high performance.

The downside of Numpy arrays is that they have a more rigid structure, and require a single numerical type (e.g. floating point values), but for a lot of scientific work, this is exactly what is needed.

The Numpy module is imported with:

In [1]:
#  import numpy

Although in the rest of this course, and in many packages, the following convention is used:

In [1]:
import numpy as np

This is because Numpy is so often used that it is shorter to type ``np`` than ``numpy``.

## Creating Numpy arrays

The easiest way to create an array is from a Python list, using the ``array`` function:

In [3]:
a = np.array([10, 20, 30, 40])

Numpy arrays have several attributes that give useful information about the array:

In [4]:
a.ndim  # number of dimensions

1

In [5]:
a.shape  # shape of the array

(4,)

In [6]:
a.dtype  # numerical type

dtype('int64')

*Note: Numpy arrays actually support more than just one integer type and one floating point type - they support signed and unsigned 8-, 16-, 32-, and 64-bit integers, and 16-, 32-, and 64-bit floating point values.*

There are several other ways to create arrays. For example, there is an ``arange`` function that can be used similarly to the built-in Python ``range`` function, with the exception that it can take floating-point input:

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3, 12, 2)

array([ 3,  5,  7,  9, 11])

In [9]:
np.arange(1.2, 4.4, 0.1)

array([ 1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3])

Another useful function is ``linspace``, which can be used to create linearly spaced values between and including limits:

In [10]:
np.linspace(11., 12., 11)

array([ 11. ,  11.1,  11.2,  11.3,  11.4,  11.5,  11.6,  11.7,  11.8,
        11.9,  12. ])

and a similar function can be used to create logarithmically spaced values between and including limits:

In [11]:
np.logspace(1., 4., 7)

array([    10.        ,     31.6227766 ,    100.        ,    316.22776602,
         1000.        ,   3162.27766017,  10000.        ])

Finally, the ``zeros`` and ``ones`` functions can be used to create arrays intially set to ``0`` and ``1`` respectively:

In [12]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

## Combining arrays

Numpy arrays can be combined numerically using the standard ``+-*/**`` operators:

In [14]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [15]:
x + 2 * y

array([ 9, 12, 15])

In [16]:
x ** y

array([  1,  32, 729])

Note that this differs from lists:

In [17]:
x = [1,2,3]
y = [4,5,6]

In [18]:
x + 2 * y

[1, 2, 3, 4, 5, 6, 4, 5, 6]

## Exercise 1

Create an array which contains 11 values logarithmically spaced between $10^{-20}$ and $10^{-10}$.

In [19]:
# your solution here
np.logspace(-20,-10,11.)

array([  1.00000000e-20,   1.00000000e-19,   1.00000000e-18,
         1.00000000e-17,   1.00000000e-16,   1.00000000e-15,
         1.00000000e-14,   1.00000000e-13,   1.00000000e-12,
         1.00000000e-11,   1.00000000e-10])

Create an array which contains the value 2 repeated 10 times (hint: there are two quick ways to do that – one is by multiplying a list, one by multiplying an array)

In [20]:
# your solution here
print(2.+np.zeros(10))
print(2.*np.ones(10))
print(np.array(10*[2.]))

[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]


Try using ``np.empty(10)`` and compare the results to ``np.zeros(10)``.  Also compare to what the people next to you got for np.empty.  What do you think is going on?

In [21]:
# your solution here
print(np.empty(10))
print(np.zeros(10))

[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Create an array containing 5 times the value 0, as a 32-bit floating point array (hint: have a look at the docs for np.zeros; the type you'd be looking for is called float32)

In [22]:
# your solution here
np.zeros(5, dtype=np.float32)

array([ 0.,  0.,  0.,  0.,  0.], dtype=float32)

## Accessing and Slicing Arrays

Similarly to lists, items in arrays can be accessed individually:

In [23]:
x = np.array([9,8,7])

In [24]:
x[0]

9

In [25]:
x[1]

8

and arrays can also be **sliced** by specifiying the start and end of the slice (where the last element is exclusive):

In [26]:
y = np.arange(10)

In [27]:
y[0:5]

array([0, 1, 2, 3, 4])

optionally specifying a step:

In [28]:
y[0:10:2]

array([0, 2, 4, 6, 8])

As for lists, the start, end, and step are all optional, and default to ``0``, ``len(array)``, and ``1`` respectively:

In [29]:
y[:5]

array([0, 1, 2, 3, 4])

In [30]:
y[::2]

array([0, 2, 4, 6, 8])

## Exercise 2

Given an array ``x`` with 10 elements, find the array ``dx`` containing 9 values where ``dx[i] = x[i+1] - x[i]``. Do this without loops!

In [31]:
# your solution here
x = np.linspace(0,9,10)**2.
print(x)
print(x[1:]-x[:9])
print(x[1:]-x[:-1])

[  0.   1.   4.   9.  16.  25.  36.  49.  64.  81.]
[  1.   3.   5.   7.   9.  11.  13.  15.  17.]
[  1.   3.   5.   7.   9.  11.  13.  15.  17.]


## Multi-dimensional arrays

Numpy can be used for multi-dimensional arrays:

In [32]:
x = np.array([[1.,2.],[3.,4.]])

In [33]:
x.ndim

2

In [34]:
x.shape

(2, 2)

In [35]:
y = np.ones([3,2,3])  # ones takes the shape of the array, not the values

In [36]:
y

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [37]:
y.shape

(3, 2, 3)

Using *np.linalg.inv()* we can calculate the **inverse** of a square array, interpreted as a matrix:

In [38]:
a=np.array([[1,2],[3,4]])

In [39]:
b=np.linalg.inv(a)

In [40]:
np.dot(a,b)

array([[  1.00000000e+00,   0.00000000e+00],
       [  8.88178420e-16,   1.00000000e+00]])

Example: The solution of the system of equations

    x   + 2*y = 5
    3*x + 4*y = 2
    
can be found using *np.dot()*, which yields the matrix product for 2-D arrays

In [41]:
np.dot(np.linalg.inv(a),[5,2])

array([-8. ,  6.5])

Multi-dimensional arrays can be sliced differently along different dimensions:

In [42]:
z = np.ones([6,6,6])

In [43]:
zz=z[::3, 1:4, :]

print(zz)
zz.shape

[[[ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]]]


(2, 3, 6)

## Functions

In addition to an array class, Numpy contains a number of **vectorized** functions, which means functions that can act on all the elements of an array, typically much faster than could be achieved by looping over the array.

For example:

In [44]:
theta = np.linspace(0., 2. * np.pi, 10)

In [45]:
theta

array([ 0.        ,  0.6981317 ,  1.3962634 ,  2.0943951 ,  2.7925268 ,
        3.4906585 ,  4.1887902 ,  4.88692191,  5.58505361,  6.28318531])

In [46]:
np.sin(theta)

array([  0.00000000e+00,   6.42787610e-01,   9.84807753e-01,
         8.66025404e-01,   3.42020143e-01,  -3.42020143e-01,
        -8.66025404e-01,  -9.84807753e-01,  -6.42787610e-01,
        -2.44929360e-16])

Another useful package is the ``np.random`` sub-package, which can be used to genenerate random numbers fast:

In [47]:
# uniform distribution between 0 and 1
np.random.random(10)

array([ 0.63170443,  0.33734632,  0.71756337,  0.61737608,  0.46075916,
        0.12305235,  0.79364448,  0.5894965 ,  0.27379061,  0.75123217])

In [48]:
# 10 values from a gaussian distribution with mean 3 and sigma 1
np.random.normal(3., 1., 10)

array([ 1.4528187 ,  3.09083909,  2.96207144,  1.77680055,  4.61256275,
        2.48456043,  3.05880556,  3.99592678,  4.7860692 ,  3.44160976])

Another very useful function in Numpy is [numpy.loadtxt](http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html) which makes it easy to read in data from column-based data. For example, given the following file:

In [49]:
%cat data/autofahrt.txt

Time Gx Gy Gz
s m/s^2 m/s^2 m/s^2
0 3.62E-04 3.62E-04 9.653301
0.2 3.62E-04 3.62E-04 9.806528
0.403 3.62E-04 -0.152865 9.806528
0.605 3.62E-04 -0.152865 9.806528
0.806 3.62E-04 -0.152865 9.806528
1.008 3.62E-04 3.62E-04 9.806528
1.208 3.62E-04 3.62E-04 9.653301
1.409 -0.152865 -0.459319 9.500074
1.61 3.62E-04 0.306816 10.112982
1.81 -0.152865 -0.459319 9.500074
2.011 3.62E-04 1.072951 9.500074
2.212 3.62E-04 -1.685135 10.266209
2.412 -0.152865 -4.136767 10.112982
2.412 -0.152865 -3.523859 9.959755
2.612 -0.152865 -3.217405 10.266209
2.814 -0.152865 -3.064178 9.653301
3.014 -0.152865 -2.910951 10.266209
3.215 3.62E-04 -2.757724 9.806528
3.416 3.62E-04 -2.910951 10.112982
3.616 3.62E-04 -3.830313 9.806528
3.817 3.62E-04 -3.830313 10.112982
4.017 3.62E-04 -3.677086 10.112982
4.217 -0.152865 -3.523859 9.806528
4.418 -0.152865 -3.523859 9.959755
4.618 3.62E-04 -4.289994 10.112982
4.819 3.62E-04 -4.136767 10.419436
4.819 3.62E-04 -4.136767 10.112982
5.019 3.62E-04 -4.289994 9.959755
5.222 -0

We can either read it in using a single multi-dimensional array:

In [50]:
data = np.loadtxt('data/autofahrt_nohd.txt')
data

array([[  0.00000000e+00,   3.62000000e-04,   3.62000000e-04,
          9.65330100e+00],
       [  2.00000000e-01,   3.62000000e-04,   3.62000000e-04,
          9.80652800e+00],
       [  4.03000000e-01,   3.62000000e-04,  -1.52865000e-01,
          9.80652800e+00],
       ..., 
       [  5.15880000e+01,   3.06816000e-01,   3.62000000e-04,
          9.95975500e+00],
       [  5.17880000e+01,   3.06816000e-01,  -3.06092000e-01,
          9.65330100e+00],
       [  5.19880000e+01,   3.06816000e-01,   3.06816000e-01,
          9.65330100e+00]])

Or we can read the individual columns:

In [5]:
time,ax,ay,az = np.loadtxt('autofahrt_nohd.txt', unpack=True)
ax

array([  3.62000000e-04,   3.62000000e-04,   3.62000000e-04,
         3.62000000e-04,   3.62000000e-04,   3.62000000e-04,
         3.62000000e-04,  -1.52865000e-01,   3.62000000e-04,
        -1.52865000e-01,   3.62000000e-04,   3.62000000e-04,
        -1.52865000e-01,  -1.52865000e-01,  -1.52865000e-01,
        -1.52865000e-01,  -1.52865000e-01,   3.62000000e-04,
         3.62000000e-04,   3.62000000e-04,   3.62000000e-04,
         3.62000000e-04,  -1.52865000e-01,  -1.52865000e-01,
         3.62000000e-04,   3.62000000e-04,   3.62000000e-04,
         3.62000000e-04,  -1.52865000e-01,  -1.52865000e-01,
         1.53589000e-01,   1.53589000e-01,  -1.52865000e-01,
         1.53589000e-01,   4.60043000e-01,   6.13270000e-01,
         4.60043000e-01,   1.53589000e-01,   3.62000000e-04,
         4.60043000e-01,   4.60043000e-01,   3.06816000e-01,
         3.06816000e-01,   1.07295100e+00,   7.66497000e-01,
         4.60043000e-01,   4.60043000e-01,   6.13270000e-01,
         4.60043000e-01,

In [52]:
time[:10]

array([ 0.   ,  0.2  ,  0.403,  0.605,  0.806,  1.008,  1.208,  1.409,
        1.61 ,  1.81 ])

In [53]:
ax[:10]

array([ 0.000362,  0.000362,  0.000362,  0.000362,  0.000362,  0.000362,
        0.000362, -0.152865,  0.000362, -0.152865])

There are additional options to **skip header rows**, **ignore comments**, **define delimiters**, or **read only certain columns**. See the documentation for more details.

## Masking

The index notation ``[...]`` is not limited to single element indexing, or multiple element slicing, but one can also pass a discrete list/array of indices:

In [54]:
x = np.array([1,6,4,7,9,3,1,5,6,7,3,4,4,3])
a = np.where(x > 3)
print(a)
print(x>3)
print(x[a])
print(x[x>3])

(array([ 1,  2,  3,  4,  7,  8,  9, 11, 12]),)
[False  True  True  True  True False False  True  True  True False  True
  True False]
[6 4 7 9 5 6 7 4 4]
[6 4 7 9 5 6 7 4 4]


which is returning a new array composed of elements 1, 2, 4, etc from the original array.

Alternatively, one can also pass a boolean array of ``True/False`` values, called a **mask**, indicating which items to keep:

In [55]:
mask = np.array([True, False, False, True, True, True, False, False, True, True, True, False, False, True])
print(x)
print(x[mask])

[1 6 4 7 9 3 1 5 6 7 3 4 4 3]
[1 7 9 3 6 7 3 3]


Now this doesn't look very useful because it is very verbose, but now consider that carrying out a comparison with the array will return such a boolean array:

In [56]:
x > 3.4

array([False,  True,  True,  True,  True, False, False,  True,  True,
        True, False,  True,  True, False], dtype=bool)

It is therefore possible to extract subsets from an array using the following simple notation:

In [57]:
x[x > 3.4]

array([6, 4, 7, 9, 5, 6, 7, 4, 4])

Conditions can be combined:

In [58]:
x[(x > 3.4) & (x < 5.5)]

array([4, 5, 4, 4])

Of course, the boolean **mask** can be derived from a different array to ``x`` as long as it is the right size:

In [59]:
x = np.linspace(-1., 1., 14)
y = np.array([1,6,4,7,9,3,1,5,6,7,3,4,4,3])

In [60]:
y[(x > -0.5) & (x < 0.4)]

array([9, 3, 1, 5, 6, 7])

Since the mask itself is an array, it can be stored in a variable and used as a mask for different arrays:

In [61]:
keep = (x > -0.5) & (x < 0.4)
x_new = x[keep]
y_new = y[keep]

In [62]:
x_new

array([-0.38461538, -0.23076923, -0.07692308,  0.07692308,  0.23076923,
        0.38461538])

In [63]:
y_new

array([9, 3, 1, 5, 6, 7])

A mask can also appear on the left hand side of an assignment:

In [64]:
y[y > 5] = 0.

In [65]:
y

array([1, 0, 4, 0, 0, 3, 1, 5, 0, 0, 3, 4, 4, 3])

## Exercise 3

The [data/munich_temperatures_average_with_bad_data.txt](data/munich_temperatures_average_with_bad_data.txt) data file gives the temperature in Munich every day for several years:

In [66]:
!head data/munich_temperatures_average_with_bad_data.txt  # shows the 10 first lines of a file

1995.00274 0.944444
1995.00548 -1.61111
1995.00821 -3.55556
1995.01095 -9.83333
1995.01369 -10.2222
1995.01643 -9.5
1995.01916 -10.2222
1995.02190 -6.61111
1995.02464 -2.94444
1995.02738 1.55556


Read in the file using ``np.loadtxt``. The data contains bad values, which you can identify by looking at the minimum and maximum values of the array. Use masking to get rid of the bad temperature values.

In [67]:

# your solution here
date, temp = np.loadtxt('data/munich_temperatures_average_with_bad_data.txt', unpack=True)
print(min(date),max(date))
print(min(temp),max(temp))
print(min(temp[temp>-99.]),max(temp[temp<99.]))
mask = (temp > -99.) & (temp < 99.)
date_new, temp_new = date[mask], temp[mask]
nbad = len(mask)-sum(mask)
print(len(mask),nbad)
print(min(temp_new),max(temp_new))

1995.00274 2013.28474
-99.0 99.0
-16.7778 27.6667
6679 60
-16.7778 27.6667
